version: "3.9"
services:
  app1:
    image: rksp5
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - NAME_APP=app1
    volumes:
      - ../upload-files:/upload-files
  app2:
    image: rksp5
    restart: on-failure
    environment:
      - NAME_APP=app2
    volumes:
      - ../upload-files:/upload-files
  app3:
    image: rksp5
    restart: on-failure
    environment:
      - NAME_APP=app3
    volumes:
      - ../upload-files:/upload-files
  app4:
    image: rksp5
    restart: on-failure
    environment:
      - NAME_APP=app4
    volumes:
      - ../upload-files:/upload-files
  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf